language: node_js
node_js:
- node
services:
- postgresql
script:
- npm install
after_script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: lSYZT6a3sp+s5RK0S1OWZdBJUSbWPf5LzpHN0248qpAChhKl20c5NjFE9DlTTtVMJa23RjOzviwLITgwOy88uNN+XudXfnmroTPluAWnx1qKQZjDFC1yF7HT84juAsreq/PfGx3hsqAreqySKJjv8FDW/LCNJZ6PkDBYY6dg+vuMmi5S/D6r4vraMjCSSqRM4Aq/reERF/I8lckiIChBg13PoOwzh/PfaWunG5KRMNX+6HaguYXSeDXop2r0ks4UPBdQoSvG5y6XqtK3t/teO6soHPKttZoPIi6hwMzZVy5bTWP1sVPq+my+iU6KTaeLKRWEwJhTAoeOdp5hmG7n9CoHrwc3MDzjUz8PPdLkBMoJm2A+tYi2iWn2G1QBeR27XlkBxRHe799wa7GzL/2rSIVOzBFzqv1AXW1M8FMMKYbhkxbm7u9rdSwpb+N3p24HBABiuxf4qn6msk2NBaDdxlt1aT6Nmk9OzCzNJSJsoljMSz74DZM+dayK07wnxqyu1R2UNhkwg/A7oF+LoCamOkh2I/DbuLfQlerPYQGmIhhoWbAaJ3jUwG5M/Q2b02D8nEwXdqUXTp0ffh+l7mJFNNZu7p4tPVONzAJfLmiC1lJJiqxziKyUJIbcJ8SAc7tDkbbKO0Btl/X/CY6o4FmYI0Ts42zbYCQFGC8P9jBVxFI=
  app: aqueous-crag-29295
  on:
    repo: froydroyce/mockr_microservice
